#This macro can not be executed standalone

/DRsim/action/useHepMC False
/DRsim/action/useCalib False

/vis/disable
/run/numberOfThreads 1
/run/initialize
/run/verbose 1

/DRsim/generator/theta 90
/DRsim/generator/phi 0

/DRsim/generator/x0 -100
/DRsim/generator/y0 0
/DRsim/generator/z0 0

/DRsim/generator/randx 0
/DRsim/generator/randy 10
/DRsim/generator/randz 10

/gun/particle e-
/gun/energy 5 GeV
/run/beamOn 2
